### ISSUE TITLE
Thumbor 7/Python 3 support?

### ISSUE THREAD

**Issue by mpdude** [intellisense/tc_pdf#2]
Can anyone tell whether this should run with Thumbor 7 without changes, or does the code have to be updated?

**Comment by mpdude** [comment]
Probably depends on https://github.com/thumbor-community/core/issues/21.

**Comment by heynemann** [comment]
I would love to have this working with t7! :( 

Great job here anyways! Adding this to awesome thumbor!

**Comment by mpdude** [comment]
I just saw „handler lists“ as a new feature in Thumbor 7.

@intellisense What exactly does `tc_core` help with? Maybe this extension here can be used with Thumbor 7 without depending on `tc_core`?

**Comment by mpdude** [comment]
@heynemann or @intellisense Could you provide some starting pointers what needs to be done?

I am not a Python programmer, but maybe I can bring this forward anyway when you point me at what needs to be done? 🤓 

Thanks!

**Comment by heynemann** [comment]
The release notes at 7.0.0 explain it
https://github.com/thumbor/thumbor/releases/tag/7.0.0

Thanks for reaching out!!!

**Comment by mpdude** [comment]
#3 would implement this

**Comment by mpdude** [comment]
#3 has been merged
